
services:  
  # FAIR Data Point server    
  fdp:
    image: fairdata/fairdatapoint:1.17.6
    hostname: fdp
    restart: always
    volumes:
      - ./fdp/application-sight2.yml:/fdp/application.yml:ro
    depends_on:
      - mongo
    networks:
      - default
      - bootstrap_sight_graphdb_net    


  fdp_client:
    image: fairdata/fairdatapoint-client:1.17.1
    hostname: fdpclient
    restart: always
    environment:
      FDP_HOST: fdp
    volumes:
      - ./fdp-client/variables.scss:/src/scss/custom/_variables.scss:ro
      - ./fdp-client/assets:/usr/share/nginx/html/assets:ro
      - ./fdp-client/favicon.ico:/usr/share/nginx/html/favicon.ico:ro
    depends_on:
      - fdp
    ports:
      - 5555:80
    networks:
      - default
      - bootstrap_sight_graphdb_net   
        
  # FAIR Data Point client	
      
  # Mongo for FDP server    
  mongo:
    image: mongo:7.0
    restart: always
    volumes:
      - sight2-mongo-data:/data/db
      - sight2-mongo-init:/docker-entrypoint-initdb.d/
    networks:
      - default
      - bootstrap_sight_graphdb_net    

      
# Define networks here
networks:
  bootstrap_sight_graphdb_net:
    external: true

volumes:
  sight2-mongo-data:
    external: true
  sight2-mongo-init:
    external: true

